### ISSUE TITLE
Undefined class constant

### ISSUE THREAD

**Issue by janstieler** [Philipp15b/php-i18n#68] opened 2020-01-18 03:49 UTC
Hi,
I have a strange problem where I can't find a solution resp. a reason for it.
I got a fatal error when I use php-i18n in my index.php:
`Fatal error: Uncaught Error: Undefined class constant 'login_failed' in /var/www/…/index.php:71 Stack trace: #0`

My call of the php-i18n extension:
```php
require_once 'vendor/philipp15b/php-i18n/i18n.class.php';

$i18n = new i18n();
$i18n->setCachePath('langcache');
$i18n->setFilePath('lang/lang_{LANGUAGE}.json');
$i18n->setPrefix('lang');
$i18n->init();

…
    return msg($typeOfMsg, lang::login_failed);
…
```
`msg` is my own errormessage function where the second paramter is the error message. 
My german languagefile in `lang/lang_de.json`:
```
{
    "login": {
        "failed": "Die Anmeldung schlug fehl! <br> Bitte füllen Sie alle Felder aus!",
        "wrongpw": "Das Password ist falsch!",
        "nopwfile": "Password Datei konnte nicht geöfnet werden!"
    }
    "browser": {
        "somethingother": "Etwas anderes..."
    }
}

```
I hope someone can give me a tip whats wrong?

Cheers

**Comment by janstieler** [comment] 2020-01-18 04:21
Hi,
I found out that it could be that this error is only the result of another failure what I have done in my php-script. But I have correct this first, to know if this is the reason.

**Comment by Philipp15b** [comment] 2020-01-22 16:08
Hi! Does the generated cache file contain your string for `login_failed`?

**Comment by janstieler** [comment] 2020-01-23 10:51
Hi,
this is what in my cache file is contain
``` <?php` class lang {
public static function __callStatic($string, $args) {
    return vsprintf(constant("self::" . $string), $args);
}
}
function lang($string, $args=NULL) {
    $return = constant("lang::".$string);
    return $args ? vsprintf($return,$args) : $return;
} ```

**Comment by HexMakina** [comment] 2021-08-11 11:11
Shoudn't constants' existence be tested before the constant() calls in cache files ?

Not sure how (or if) it would impact performances, so I added two methods to my fork: compileCallStatic() and compileFunction() to allow cache files functions to be redefined when extending i18n.

For instance., in my Lezer class, the compileFunction returns 
    
    . "function ".$this->prefix .'($string, $args=NULL) {'."\n"
    . '    if (!defined("'.$this->prefix.'::".$string))'
    . '       return $string;'
    . '    $return = constant("'.$this->prefix.'::".$string);'."\n"
    . '    return $args ? vsprintf($return,$args) : $return;'
    . "\n}";

**Comment by Philipp15b** [comment] 2021-10-03 18:56
It seems that something in the generated code went wrong. @janstieler did you fix the issue yet? I'm going to close this, but if the issue is still present, I'll re-open it.

@HexMakina I don't think just returning the name of the constant is good if it's undefined. I like to have my failure cases explicit, with a runtime error.

**Closed by Philipp15b** 2021-10-03 18:56 UTC
